const Movies = [
    {
    imgSrc:'https://images.news18.com/ibnlive/uploads/2021/08/1628438277_islamic-new-year.jpg',
    name:'aniket',
    sideAddress:'',
    movieName:'',
    },
    { 
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'abhishek',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'suraj',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'',
        sideAddress:'',
        movieName:'',
    },
    {
        imgSrc:'https://www.netflix.com/in/title/81144150',
        name:'anil',
        sideAddress:'',
        movieName:'',
    }


]
export default Movies;